INSERT INTO [OPTION] VALUES('Следующее значение параметра',0)
INSERT INTO [OPTION] VALUES('Версии таблиц',1)
INSERT INTO [OPTION] VALUES('Официанты',2)
INSERT INTO [OPTION] VALUES('Цеха',3)
INSERT INTO [OPTION] VALUES('Типы ингредиентов',4)
INSERT INTO [OPTION] VALUES('Типы напитков',5)
INSERT INTO [OPTION] VALUES('Типы блюд',6)
INSERT INTO [OPTION] VALUES('Ингредиенты',7)
INSERT INTO [OPTION] VALUES('Напитки',8)
INSERT INTO [OPTION] VALUES('Блюда',9)
INSERT INTO [OPTION] VALUES('Ланч блюда',10)
INSERT INTO [OPTION] VALUES('Рецепты',11)
INSERT INTO [OPTION] VALUES('Ланч рецепты',12)
INSERT INTO [OPTION] VALUES('Напитки с группировкой',13)

INSERT INTO [FIELD_NAME] VALUES('room_table','Стол')
INSERT INTO [FIELD_NAME] VALUES('ingredient','Ингредиент')
INSERT INTO [FIELD_NAME] VALUES('name','Название')
INSERT INTO [FIELD_NAME] VALUES('section','Разделы')
INSERT INTO [FIELD_NAME] VALUES('order','Заказ')
INSERT INTO [FIELD_NAME] VALUES('show','Видимость')
INSERT INTO [FIELD_NAME] VALUES('show1','Показан')
INSERT INTO [FIELD_NAME] VALUES('show0','Скрыт')
INSERT INTO [FIELD_NAME] VALUES('price','Стоимость')
INSERT INTO [FIELD_NAME] VALUES('available','Доступность')
INSERT INTO [FIELD_NAME] VALUES('available0','Не показывать')
INSERT INTO [FIELD_NAME] VALUES('available1','Не доступен')
INSERT INTO [FIELD_NAME] VALUES('available2','Доступен')
INSERT INTO [FIELD_NAME] VALUES('short_name','Название для чека')
INSERT INTO [FIELD_NAME] VALUES('type','Тип')
INSERT INTO [FIELD_NAME] VALUES('typedp','За порцию')
INSERT INTO [FIELD_NAME] VALUES('typedi','За 1шт')
INSERT INTO [FIELD_NAME] VALUES('typefi','За 1шт')
INSERT INTO [FIELD_NAME] VALUES('typefp','За 100г')
INSERT INTO [FIELD_NAME] VALUES('portion','Деление порций')
INSERT INTO [FIELD_NAME] VALUES('startPortion','Начальное значение порций')
INSERT INTO [FIELD_NAME] VALUES('pricePortion','Порция для расчёта')
INSERT INTO [FIELD_NAME] VALUES('workshop','Цех')
INSERT INTO [FIELD_NAME] VALUES('menu_item','Позиции меню')
INSERT INTO [FIELD_NAME] VALUES('dttm','Дата')
INSERT INTO [FIELD_NAME] VALUES('fixed_price','Фиксированная цена')
INSERT INTO [FIELD_NAME] VALUES('sale','Скидка %')
INSERT INTO [FIELD_NAME] VALUES('sale_price','Цена со скидкой')
INSERT INTO [FIELD_NAME] VALUES('number','Номер')
INSERT INTO [FIELD_NAME] VALUES('waiter','Официант')
INSERT INTO [FIELD_NAME] VALUES('people_count','Количество человек')
INSERT INTO [FIELD_NAME] VALUES('open_time','Время открытия')
INSERT INTO [FIELD_NAME] VALUES('close_time','Время закрытия')
INSERT INTO [FIELD_NAME] VALUES('order_time','Время заказа')
INSERT INTO [FIELD_NAME] VALUES('cancel_time','Время отмены')
INSERT INTO [FIELD_NAME] VALUES('imptest','Аванс')
INSERT INTO [FIELD_NAME] VALUES('total','Итого')
INSERT INTO [FIELD_NAME] VALUES('bill','Счёт')
INSERT INTO [FIELD_NAME] VALUES('count','Количество')
INSERT INTO [FIELD_NAME] VALUES('away','На вынос')
INSERT INTO [FIELD_NAME] VALUES('later','Позже')
INSERT INTO [FIELD_NAME] VALUES('bill_item','Позиция счёта')
INSERT INTO [FIELD_NAME] VALUES('add','Статус')
INSERT INTO [FIELD_NAME] VALUES('add0','Убран')
INSERT INTO [FIELD_NAME] VALUES('add1','Добавлен')
INSERT INTO [FIELD_NAME] VALUES('isadmin','Роль')
INSERT INTO [FIELD_NAME] VALUES('isadmin0','Официант')
INSERT INTO [FIELD_NAME] VALUES('isadmin1','Администратор')
